# Generated by Django 2.2.4 on 2019-08-10 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytestapp', '0002_auto_20190808_0907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermessage',
            name='status_code',
        ),
        migrations.AddField(
            model_name='usermessage',
            name='status',
            field=models.BooleanField(default=0),
        ),
    ]
